### ISSUE TITLE
declareReferenced option doesn't work if the reference isn't a URI

### ISSUE THREAD

**Issue by arosequist** [bcherny/json-schema-to-typescript#103] opened 2017-07-12 18:00 UTC
[This](https://github.com/arosequist/json-schema-to-typescript/compare/master...arosequist:declare-referenced-bug?diff=unified&name=declare-referenced-bug#diff-d2ee835d7d6308692fb6c1d10afe49cc) is a modified version of `test/e2e/ref.1.ts`. The second test (with `declareReferenced: false`) fails, because `InlineReference` is still being included in the output.

Is this behavior expected, or is it a bug?

**Comment by bcherny** [comment] 2017-07-12 19:05
You are correct - it should be called `declareExternalReferenced`. What is the expected behavior for your use case?

**Comment by arosequist** [comment] 2017-07-14 15:15
Based on the name and docs, I just expected this parameter to determine if schemas referenced via `$ref` would be declared, regardless of where that referenced schema lives.

**Comment by bcherny** [comment] 2017-07-14 18:35
Looking through the code more, here's what's going on:

There are 3 reasons an interface/type will be declared as a separate schema (not as part of the main schema): (1) it has a `title`, (2) it has an `id`, (3) it is a subschema. Interfaces always fall into (2), and sometimes into (1) and (3) as well - this is ensured in the normalization phase, before parsing and ref resolution.

`declareReferenced` should apply to both internally and externally defined types and interfaces. Today, `declareReferenced` applies to just internally and externally defined interfaces (not types).

The reason is that because we resolve references before passing the schema to the parser, the parser can't make a distinction between internal and external. It mostly works for interfaces today, but does not work for types. This is because we use a heuristic: if hasStandaloneName and (standaloneName is rootSchemaName or declareReferenced), then generate a declaration for the interface. This heuristic is not great, because it will also fail to declare interfaces for non-referenced subschemas, and it will declare referenced types.

There are 3 possible expected behaviors:

1. `declareReferenced` should apply to everything that would have been declared outside of the main schema. It should be renamed to `declareOthers`, and the generator should be updated to respect this stricter rule. This would require a change in the generator, and nothing else.
2. `declareReferenced` should apply to all types and schemas referenced via `$ref`. This would require setting a flag on every property that was resolved by the ref resolver, and using that flag rather than a heuristic when deciding whether or not to generate the given type/interface. I'm not sure how setting that flag would work without forking json-schema-ref-parser to add a post-resolve hook (I doubt this hook will be useful to anyone besides us).
3. Like (2), but split it out into `declareReferencedTypes` and `declareReferencedInterfaces`

(2) is probably the right behavior here. I will try to get to this, but can't promise anything soon.

@arosequist In the meantime, is this causing issues for you, or is it just a deviation from expected behavior?

**Comment by bcherny** [comment] 2017-07-14 19:39
@arosequist It was actually easier than expected. When you have a chance, try this branch and let me know if it's what you expected - https://github.com/bcherny/json-schema-to-typescript/tree/103.

From playing around with it a bit, I think I'm in favor of renaming `declareReferenced` to `declareExternallyReferenced`. I'm having trouble thinking of a use case where you wouldn't want to declare internal references (because by definition, they were not declared elsewhere, and any generated types will necessarily be broken without them).

**Comment by bcherny** [comment] 2017-07-20 20:13
@arosequist Can you take a look?

**Comment by arosequist** [comment] 2017-07-21 14:35
Yeah, that seems to fix it!

Our use case is probably an odd one -- we loop through all the `definitions` in a schema object and run `json-schema-to-typescript` on them, which causes duplicates. We loop through them because there are a couple of use cases where we want some slightly different output, so we skip `json-schema-to-typescript` and do our own processing on those. [1]

Since that's probably not common, I think renaming `declareReferenced` to `declareExternallyReferenced` makes sense (or even just clarifying it in the docs).

[1] We'll probably be revisiting our approach to this soon anyway, so we might not even have this use case for much longer.

**Comment by bcherny** [comment] 2017-07-21 20:58
Out of curiosity, what's your use case for only looping through `definitions`?

**Closed** 2017-07-21 20:57 UTC
Labels: in discussion
