### ISSUE TITLE
Schema fails to match JSONSchema4

### ISSUE THREAD

**Issue by retorquere** [bcherny/json-schema-to-typescript#253] opened 2019-09-04 06:58 UTC
I have this schema:

```
{
  "type": "object",
  "properties": {
    "type": {
      "enum": [
        "collection",
        "library"
      ]
    },
    "id": {
      "type": "integer"
    },
    "path": {
      "type": "string",
      "minLength": 1
    },
    "status": {
      "enum": [
        "scheduled",
        "running",
        "done",
        "error"
      ]
    },
    "translatorID": {
      "type": "string",
      "minLength": 1
    },
    "exportNotes": {
      "type": "boolean",
      "default": false
    },
    "useJournalAbbreviation": {
      "type": "boolean",
      "default": false
    },
    "DOIandURL": {
      "enum": [
        "both",
        "doi",
        "url"
      ]
    },
    "asciiBibLaTeX": {
      "type": "boolean"
    },
    "asciiBibTeX": {
      "type": "boolean"
    },
    "biblatexExtendedNameFormat": {
      "type": "boolean"
    },
    "bibtexParticleNoOp": {
      "type": "boolean"
    },
    "bibtexURL": {
      "enum": [
        "off",
        "note",
        "url"
      ]
    },
    "error": {
      "type": "string",
      "default": ""
    },
    "meta": {
      "type": "object"
    },
    "$loki": {
      "type": "integer"
    }
  },
  "required": [
    "type",
    "id",
    "path",
    "status",
    "translatorID",
    "exportNotes",
    "useJournalAbbreviation",
    "DOIandURL",
    "asciiBibLaTeX",
    "asciiBibTeX",
    "biblatexExtendedNameFormat",
    "bibtexParticleNoOp",
    "bibtexURL"
  ],
  "additionalProperties": false
}
```

but when I pass it to `compile` I get

```
error TS2345: Argument of type '{ type: string; properties: any; required: any[]; additionalProperties: boolean; }' is not assignable to parameter of type 'JSONSchema4'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type '"string" | "number" | "boolean" | "object" | "integer" | "array" | "null" | "any" | JSONSchema4TypeName[]'.
```

**Comment by retorquere** [comment] 2019-09-04 14:04
If I ignore the typings and just use javascript, it does work:

```
var jsonSchemaToTypescript = require("json-schema-to-typescript")
var compile = jsonSchemaToTypescript.compile;

var mySchema = {
  "type": "object",
  "properties": {
    "type": {
      "enum": [
        "collection",
        "library"
      ]
    },
    "id": {
      "type": "integer"
    },
    "path": {
      "type": "string",
      "minLength": 1
    },
    "status": {
      "enum": [
        "scheduled",
        "running",
        "done",
        "error"
      ]
    },
    "translatorID": {
      "type": "string",
      "minLength": 1
    },
    "exportNotes": {
      "type": "boolean",
      "default": false
    },
    "useJournalAbbreviation": {
      "type": "boolean",
      "default": false
    },
    "DOIandURL": {
      "enum": [
        "both",
        "doi",
        "url"
      ]
    },
    "asciiBibLaTeX": {
      "type": "boolean"
    },
    "asciiBibTeX": {
      "type": "boolean"
    },
    "biblatexExtendedNameFormat": {
      "type": "boolean"
    },
    "bibtexParticleNoOp": {
      "type": "boolean"
    },
    "bibtexURL": {
      "enum": [
        "off",
        "note",
        "url"
      ]
    },
    "error": {
      "type": "string",
      "default": ""
    },
    "meta": {
      "type": "object"
    },
    "$loki": {
      "type": "integer"
    }
  },
  "required": [
    "type",
    "id",
    "path",
    "status",
    "translatorID",
    "exportNotes",
    "useJournalAbbreviation",
    "DOIandURL",
    "asciiBibLaTeX",
    "asciiBibTeX",
    "biblatexExtendedNameFormat",
    "bibtexParticleNoOp",
    "bibtexURL"
  ],
  "additionalProperties": false
};

compile(mySchema, 'MySchema')
  .then(ts => console.log(ts))
```

**Comment by dbrockman** [comment] 2019-12-02 13:07
@retorquere  This is not a bug. You are passing the type `string` to the union type above `"string" | "number" | "boolean" | ...`

You can fix it two ways.
1. import the `JSONSchema` interface and set that as the type of `mySchema`: `var mySchema: JSONSchema = { ... }`
2. you can also just inline the object in the function call: `compile({ ... }, 'MySchema')`

**Comment by retorquere** [comment] 2019-12-02 13:49
I don't quite follow? I'm only passing supported types for `type`, right? Shouldn't typescript figure out I'm passing a compatible value?

So I'd have to do
```
import { JSONSchema, compile } from 'json-schema-to-typescript'
const mySchema: JSONSchema = {...}
compile(mySchema)
```
?

**Comment by dbrockman** [comment] 2020-02-18 11:20
@retorquere The problem is that when you assign an object to a var, typescript will use a more general type for that var. For example:

```ts
let x = 'foo';
// The type of `x` is `string`, not `"foo"`
```

The type `JSONSchema` specifies that the property "type" must have the type `"string" | "number" | "boolean" | and so on...` so the more general type `string` cannot be assigned to this narrow subset of strings.

I know it's a bit confusing... Here's another example that might show it a bit more clearly.

```ts
// arg must be one of the strings "foo" or "bar"
function exampleFunc(arg: 'foo' | 'bar') {
}

// This will result in an error.
// Typescript has marked the type of my_str as `string` but that is too broad for exampleFunc.
let my_str = 'foo';
exampleFunc(my_str);

// This is ok because typescript can see that the string is one of the allowed strings in the type.
exampleFunc('foo');

// This is also ok as of typescript version 3.4.
// It will narrow the type to be `"foo"` instead of `string`.
// See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions
let my_str_2 = 'foo' as const;
exampleFunc(my_str_2);
```

**Closed** 2020-11-29 22:58 UTC
