### ISSUE TITLE
Top-level `$ref` throws exception

### ISSUE THREAD

**Issue by letmaik** [bcherny/json-schema-to-typescript#415] opened 2021-10-19 19:32 UTC
Repro:
```json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$ref": "#/$defs/Document",

    "$defs": {
        "Document": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "createdBy": {
                    "type": "string"
                }
            }
        }
    }
}
```

Error:
```        
Error: Refs should have been resolved by the resolver! { '$schema': 'https://json-schema.org/draft/2019-09/schema',
  '$ref': '#',
  id: 'Demo',
  definitions: 
   { Document: 
      { type: 'object',
        properties: [Object],
        required: [],
        additionalProperties: true } } }
    at parseNonLiteral (bundle.js:14526)
    at parseAsTypeWithCache (bundle.js:14437)
    at Object.parse (bundle.js:14396)
    at Object.<anonymous> (bundle.js:41815)
    at step (bundle.js:41715)
    at Object.next (bundle.js:41696)
    at fulfilled (bundle.js:41687)
```

**Comment by jrehwaldt** [comment] 2022-01-03 10:44
I believe this is a duplicate of #132.

**Closed** 2022-01-03 11:05 UTC
