### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by donaldpipowitch** [bcherny/json-schema-to-typescript#35] opened 2016-09-21 06:24 UTC
Try to `compileFromFile` [this schema](https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json) throws.

```
/Users/foo/webpack/node_modules/lodash/lodash.js:2591
    function baseClone(value, isDeep, isFull, customizer, key, object, stack) {
                      ^

RangeError: Maximum call stack size exceeded
    at baseClone (/Users/foo/webpack/node_modules/lodash/lodash.js:2591:23)
    at /Users/foo/webpack/node_modules/lodash/lodash.js:2644:34
    at arrayEach (/Users/foo/webpack/node_modules/lodash/lodash.js:520:11)
    at baseClone (/Users/foo/webpack/node_modules/lodash/lodash.js:2638:7)
    at baseMergeDeep (/Users/foo/webpack/node_modules/lodash/lodash.js:3627:24)
    at /Users/foo/webpack/node_modules/lodash/lodash.js:3562:11
    at arrayEach (/Users/foo/webpack/node_modules/lodash/lodash.js:520:11)
    at baseMerge (/Users/foo/webpack/node_modules/lodash/lodash.js:3555:7)
    at /Users/foo/webpack/node_modules/lodash/lodash.js:13254:7
    at Function.<anonymous> (/Users/foo/webpack/node_modules/lodash/lodash.js:4781:13)
```

The webpack schema is quite heavy. Perfect stress test to optimize ;) Note that you have to [delete this enum](https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json#L638) because of https://github.com/bcherny/json-schema-to-typescript/issues/34 to get this working for now.

**Comment by darcyparker** [comment] 2016-09-21 19:31
An initial guess: https://github.com/bcherny/json-schema-to-typescript/blob/master/src/index.ts#L313 because `merge()` uses `baseClone()`. 

* [merge calls baseMergeDeep](https://github.com/lodash/lodash/blob/master/dist/lodash.js#L3562)
* [baseMergeDeep calls baseClone](https://github.com/lodash/lodash/blob/master/dist/lodash.js#L3627) and baseClone() is recursive with a warning about stack limits because of its recurssive nature.
* And there is a bit more recursion in baseMergeDeep().

Is the full stack trace shown above? I didn't attempt to reproduce... but made this guess by looking for recursive lodash methods used by this project.

I don't have time to look at this further today... and may not in next few days. But wanted to share my initial findings. I think https://github.com/bcherny/json-schema-to-typescript/blob/master/src/index.ts#L313 can be refactored to not use lodash and this may solve the problem.

**Comment by donaldpipowitch** [comment] 2016-09-21 20:01
> Is the full stack trace shown above? 

Yes.

**Comment by darcyparker** [comment] 2016-09-27 15:37
FYI: I have a test in place that blows the stack. https://github.com/darcyparker/json-schema-to-typescript/commit/db2b30c34fa3fce975c05a0c3b725b51c9dc3e1d

**Comment by darcyparker** [comment] 2016-09-27 17:19
Updating link mentioned above because new commits changed the line number: https://github.com/bcherny/json-schema-to-typescript/blob/1aa73177ca6c3d0cf6963f9ff9e42e0ed57668cc/src/index.ts#L274 (This link points to a specific commit's file's line number)

**Comment by darcyparker** [comment] 2016-09-27 19:18
A WIP that improves call stack usage is available for review. Please let me know if it helps.

**Comment by bcherny** [comment] 2016-09-28 05:42
@donaldpipowitch You're getting a call stack exceeded error because you have a bunch of circular references in your schema

- https://github.com/webpack/webpack/blob/e5ae047334d187b5fe17318fbc5ef58f6e500419/schemas/webpackOptionsSchema.json#L655
- https://github.com/webpack/webpack/blob/e5ae047334d187b5fe17318fbc5ef58f6e500419/schemas/webpackOptionsSchema.json#L706
- https://github.com/webpack/webpack/blob/e5ae047334d187b5fe17318fbc5ef58f6e500419/schemas/webpackOptionsSchema.json#L729
etc

I'll add a circular reference checker to the ref resolver (the resolver is very bare bones as is). In the meantime, if you get rid of the circular references, your schema seems to compile fine.

**Comment by donaldpipowitch** [comment] 2016-09-28 07:01
Thank you both. I'll close this issue than as it is probably a problem with the schema and its circular references.

**Comment by donaldpipowitch** [comment] 2016-09-28 07:04
Short question: Is this really a circular reference? Doesn't [this](https://github.com/webpack/webpack/blob/e5ae047334d187b5fe17318fbc5ef58f6e500419/schemas/webpackOptionsSchema.json#L655) point to [this definition](https://github.com/webpack/webpack/blob/e5ae047334d187b5fe17318fbc5ef58f6e500419/schemas/webpackOptionsSchema.json#L101)?

**Comment by darcyparker** [comment] 2016-09-28 15:27
Side question: Do you know of a tool that generates a graph of a json schema? (For example something that creates graphml for http://www.yworks.com/products/yed or http://www.cytoscape.org/, or alternatively dot files for http://graphviz.org/ dot) If not, I am thinking this could be an interesting project.  It's one thing to write circular reference detection and give feedback when you walk to a node that you've been to before... but visually seeing it in a picture could be helpful.)

**Comment by bcherny** [comment] 2016-09-28 17:28
@donaldpipowitch You're right - I misread the schema. This issue is with resolving local $refs, not with a circular definition. Filed https://github.com/bcherny/json-schema-to-typescript/issues/44

@darcyparker Not off the top of my head, but it would be pretty trivial to write one I think.

**Closed** 2016-09-28 21:44 UTC
Labels: enhancement
